class Func(object):
    f_CheckWorkMode = "0"
    f_DevGetSelfPara = "1"
    f_DevEncoding  = "2"
    f_DevDetection = "3"
    f_DevSettingPara = "4"
    f_DevDeteCheckVA = "5"
    f_DevDeteLogLineVA = "6"
    f_DevDeteCheck = "7"
    f_DevDeteCheckVA = "8"
    f_DevDeteCheckVA = "9"