class Func(object):
    f_CheckWorkMode = "0"
    f_DevGetSelfPara = "1"
    f_DevEncoding  = "2"
    f_DevDetection = "3"
    f_DevSettingPara = "4"
    f_DevDetRepLineVA = "5"
    f_DevDetLogLineLoseA = "6"
    f_DevDetLogUid2BridgeSta = "7"
    f_DevDetLogUid1BridgeSta = "8"
    f_DevDetLogUid2FireV = "9"
    f_DevDetLogUid2FireA = "A"
    f_DevDetLogUid1FireV = "9"
    f_DevDetLogUid1FireA = "A"
