# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Learn\2021\719\Python\Terminal\Protocol.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProtocolDialog(object):
    def setupUi(self, ProtocolDialog):
        ProtocolDialog.setObjectName("ProtocolDialog")
        ProtocolDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ProtocolDialog.resize(330, 168)
        ProtocolDialog.setStyleSheet("    background-color:#e9f1f6;")
        self.groupBox = QtWidgets.QGroupBox(ProtocolDialog)
        self.groupBox.setGeometry(QtCore.QRect(8, 14, 309, 139))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.comboBox_selectComNum = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_selectComNum.setGeometry(QtCore.QRect(9, 32, 289, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_selectComNum.sizePolicy().hasHeightForWidth())
        self.comboBox_selectComNum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_selectComNum.setFont(font)
        self.comboBox_selectComNum.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.comboBox_selectComNum.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_selectComNum.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(214, 234, 239);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(130, 195, 195);\n"
"}")
        self.comboBox_selectComNum.setEditable(False)
        self.comboBox_selectComNum.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_selectComNum.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_selectComNum.setFrame(True)
        self.comboBox_selectComNum.setObjectName("comboBox_selectComNum")
        self.comboBox_selectComNum.addItem("")
        self.btn_SwitchSerial = QtWidgets.QPushButton(self.groupBox)
        self.btn_SwitchSerial.setGeometry(QtCore.QRect(8, 84, 291, 53))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.btn_SwitchSerial.setFont(font)
        self.btn_SwitchSerial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_SwitchSerial.setAutoFillBackground(False)
        self.btn_SwitchSerial.setStyleSheet("QPushButton:hover{\n"
"    background-color: #c0ebd7;\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    border: 2px solid #3a8ee6;\n"
"    color: #409eff;\n"
"}\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #808080;\n"
"    padding: 10px;\n"
"    border-radius: 10px;\n"
"}")
        self.btn_SwitchSerial.setAutoDefault(False)
        self.btn_SwitchSerial.setObjectName("btn_SwitchSerial")

        self.retranslateUi(ProtocolDialog)
        QtCore.QMetaObject.connectSlotsByName(ProtocolDialog)

    def retranslateUi(self, ProtocolDialog):
        _translate = QtCore.QCoreApplication.translate
        ProtocolDialog.setWindowTitle(_translate("ProtocolDialog", "Dialog"))
        self.groupBox.setTitle(_translate("ProtocolDialog", "端口设置"))
        self.comboBox_selectComNum.setCurrentText(_translate("ProtocolDialog", "JLink CDC UART Port (COM255)"))
        self.comboBox_selectComNum.setItemText(0, _translate("ProtocolDialog", "JLink CDC UART Port (COM255)"))
        self.btn_SwitchSerial.setText(_translate("ProtocolDialog", "打开串口"))
        self.btn_SwitchSerial.setShortcut(_translate("ProtocolDialog", "Ctrl+1"))
