# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Learing\2021\719\PythonCode\Detector\SerialUtil.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_SerialSettings(object):
    def setupUi(self, dialog_SerialSettings):
        dialog_SerialSettings.setObjectName("dialog_SerialSettings")
        dialog_SerialSettings.resize(746, 536)
        self.pushBtn_serialSenddata = QtWidgets.QPushButton(dialog_SerialSettings)
        self.pushBtn_serialSenddata.setGeometry(QtCore.QRect(205, 105, 120, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushBtn_serialSenddata.setFont(font)
        self.pushBtn_serialSenddata.setObjectName("pushBtn_serialSenddata")
        self.label_operator_4 = QtWidgets.QLabel(dialog_SerialSettings)
        self.label_operator_4.setGeometry(QtCore.QRect(485, 40, 91, 29))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_operator_4.setFont(font)
        self.label_operator_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_operator_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_operator_4.setObjectName("label_operator_4")
        self.pushBtn_clearSerialRecv = QtWidgets.QPushButton(dialog_SerialSettings)
        self.pushBtn_clearSerialRecv.setGeometry(QtCore.QRect(205, 170, 120, 36))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushBtn_clearSerialRecv.setFont(font)
        self.pushBtn_clearSerialRecv.setObjectName("pushBtn_clearSerialRecv")
        self.information = QtWidgets.QTextBrowser(dialog_SerialSettings)
        self.information.setGeometry(QtCore.QRect(330, 70, 401, 136))
        self.information.setObjectName("information")
        self.lineEdit_serialSendArea = QtWidgets.QLineEdit(dialog_SerialSettings)
        self.lineEdit_serialSendArea.setGeometry(QtCore.QRect(205, 70, 120, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_serialSendArea.setFont(font)
        self.lineEdit_serialSendArea.setText("")
        self.lineEdit_serialSendArea.setObjectName("lineEdit_serialSendArea")
        self.pushBtn_clearSerialSend = QtWidgets.QPushButton(dialog_SerialSettings)
        self.pushBtn_clearSerialSend.setGeometry(QtCore.QRect(205, 135, 120, 36))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushBtn_clearSerialSend.setFont(font)
        self.pushBtn_clearSerialSend.setObjectName("pushBtn_clearSerialSend")

        self.retranslateUi(dialog_SerialSettings)
        QtCore.QMetaObject.connectSlotsByName(dialog_SerialSettings)

    def retranslateUi(self, dialog_SerialSettings):
        _translate = QtCore.QCoreApplication.translate
        dialog_SerialSettings.setWindowTitle(_translate("dialog_SerialSettings", "Dialog"))
        self.pushBtn_serialSenddata.setText(_translate("dialog_SerialSettings", "发送数据"))
        self.label_operator_4.setText(_translate("dialog_SerialSettings", "接收显示"))
        self.pushBtn_clearSerialRecv.setText(_translate("dialog_SerialSettings", "清除接收"))
        self.pushBtn_clearSerialSend.setText(_translate("dialog_SerialSettings", "清除发送"))
